//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Reflection;

   

    public partial class ExpenseData
    {
        
        public int ExpenseId { get; set; }

        [Required(ErrorMessage = "*Expense Title Required")]
        public string Title { get; set; }

        [Required(ErrorMessage = "*Expense Description Required")]
        public string Description { get; set; }

        [Required(ErrorMessage = "*Expense Amount Required")]
        public Nullable<int> Amount { get; set; }

        public Nullable<int> CategoryId { get; set; }
        public string date_and_time { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ExpenseData ExpenseData1 { get; set; }
        public virtual ExpenseData ExpenseData2 { get; set; }
    }
}
